#!/usr/bin/env node
/**
 * Generate reference documentation from the manifests themselves.
 *
 * Hand-written input tables rot the moment someone adds an input, and a rotted table is
 * worse than none — people trust it. So the tables are generated from `action.yml` and
 * `workflow_call` and CI fails when they drift (`--check`), the same contract tf-tools has
 * with terraform-docs.
 *
 * What it writes:
 *   • `actions/<name>/README.md`         — one page per action
 *   • `docs/WORKFLOWS.md`                — reference for every reusable workflow
 *   • the catalog tables in `README.md`  — between the AUTOGEN markers
 *
 * Prose lives in the leading comment block of each manifest and is carried into the page,
 * so the explanation sits next to the thing it explains and can't drift from it.
 *
 * Usage:
 *   node scripts/gen-docs.mjs           write the files
 *   node scripts/gen-docs.mjs --check   exit 1 if anything would change
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join, relative, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const ACTIONS_DIR = join(ROOT, 'actions');
const WORKFLOWS_DIR = join(ROOT, '.github', 'workflows');
const REPO = 'patrickisgreat/actions-toolkit';
const PIN = 'v1';

const CHECK = process.argv.includes('--check');
const drifted = [];
const written = [];

// ── helpers ────────────────────────────────────────────────────────────────────────────

/**
 * Pull the leading `#` comment block out of a manifest — everything before the first
 * non-comment, non-blank line. That block is the author's explanation of the file and
 * becomes the page's prose.
 */
function leadingComment(source) {
  const lines = [];
  for (const line of source.split('\n')) {
    if (line.startsWith('#')) {
      lines.push(line.replace(/^#\s?/, ''));
      continue;
    }
    if (line.trim() === '' && lines.length === 0) continue;
    break;
  }
  // Trailing blank comment lines are separators, not content.
  while (lines.length && lines[lines.length - 1].trim() === '') lines.pop();
  return lines.join('\n').trim();
}

/** Escape a value for a Markdown table cell. */
function cell(value) {
  if (value === undefined || value === null || value === '') return '—';
  return String(value)
    .replace(/\|/g, '\\|')
    .replace(/\r?\n/g, ' ')
    .trim();
}

function codeCell(value) {
  if (value === undefined || value === null || value === '') return '—';
  return `\`${String(value).replace(/\|/g, '\\|').replace(/`/g, '')}\``;
}

function inputTable(inputs, { withType = false } = {}) {
  const entries = Object.entries(inputs ?? {});
  if (entries.length === 0) return '_No inputs._\n';
  const header = withType
    ? '| Input | Type | Required | Default | Description |\n|---|---|---|---|---|\n'
    : '| Input | Required | Default | Description |\n|---|---|---|---|\n';
  const rows = entries.map(([name, spec]) => {
    const required = spec?.required ? '**yes**' : 'no';
    const def = spec?.default === '' ? '`""`' : codeCell(spec?.default);
    return withType
      ? `| \`${name}\` | \`${spec?.type ?? 'string'}\` | ${required} | ${def} | ${cell(spec?.description)} |`
      : `| \`${name}\` | ${required} | ${def} | ${cell(spec?.description)} |`;
  });
  return header + rows.join('\n') + '\n';
}

function outputTable(outputs) {
  const entries = Object.entries(outputs ?? {});
  if (entries.length === 0) return '_No outputs._\n';
  return (
    '| Output | Description |\n|---|---|\n' +
    entries.map(([name, spec]) => `| \`${name}\` | ${cell(spec?.description)} |`).join('\n') +
    '\n'
  );
}

function secretTable(secrets) {
  const entries = Object.entries(secrets ?? {});
  if (entries.length === 0) return '';
  return (
    '\n### Secrets\n\n| Secret | Required | Description |\n|---|---|---|\n' +
    entries
      .map(([name, spec]) => `| \`${name}\` | ${spec?.required ? '**yes**' : 'no'} | ${cell(spec?.description)} |`)
      .join('\n') +
    '\n'
  );
}

/** Write, or record drift under --check. */
function emit(path, content) {
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (existing === content) return;
  if (CHECK) {
    drifted.push(relative(ROOT, path));
    return;
  }
  writeFileSync(path, content);
  written.push(relative(ROOT, path));
}

const GENERATED_NOTE =
  '<!-- Generated by scripts/gen-docs.mjs. Edit the manifest, then run `make docs`. -->';

// ── per-action pages ───────────────────────────────────────────────────────────────────

const actions = readdirSync(ACTIONS_DIR)
  .map((name) => ({ name, dir: join(ACTIONS_DIR, name) }))
  .filter(({ dir }) => statSync(dir).isDirectory() && existsSync(join(dir, 'action.yml')))
  .sort((a, b) => a.name.localeCompare(b.name));

for (const { name, dir } of actions) {
  const source = readFileSync(join(dir, 'action.yml'), 'utf8');
  const doc = parse(source);
  const prose = leadingComment(source);

  // A minimal, correct usage block beats a hand-maintained one that drifts: required
  // inputs only, since those are the ones a caller cannot omit.
  const required = Object.entries(doc.inputs ?? {}).filter(([, s]) => s?.required);
  const usageInputs =
    required.length > 0
      ? '\n  with:\n' + required.map(([k]) => `    ${k}: # ${cell(doc.inputs[k].description)}`).join('\n')
      : '';

  const page = `# ${doc.name}

${GENERATED_NOTE}

${doc.description}

\`\`\`yaml
- uses: ${REPO}/actions/${name}@${PIN}${usageInputs}
\`\`\`

## How it works

${prose || '_No notes._'}

## Inputs

${inputTable(doc.inputs)}
## Outputs

${outputTable(doc.outputs)}
---

_Part of [actions-toolkit](../../README.md). See [docs/CONSUMING.md](../../docs/CONSUMING.md) for pinning and versioning._
`;

  emit(join(dir, 'README.md'), page);
}

// ── reusable workflow reference ────────────────────────────────────────────────────────

const workflows = readdirSync(WORKFLOWS_DIR)
  .filter((f) => (f.endsWith('.yml') || f.endsWith('.yaml')) && !f.startsWith('self-'))
  .sort()
  .map((file) => {
    const source = readFileSync(join(WORKFLOWS_DIR, file), 'utf8');
    const doc = parse(source);
    return { file, source, doc, call: (doc?.on ?? doc?.true)?.workflow_call };
  })
  .filter((w) => w.call !== undefined);

const workflowPages = workflows
  .map(({ file, source, doc, call }) => {
    const slug = basename(file, '.yml');
    return `## \`${slug}\`

${doc.name} — ${leadingComment(source).split('\n')[0]}

\`\`\`yaml
jobs:
  ${slug.replace(/-/g, '_')}:
    uses: ${REPO}/.github/workflows/${file}@${PIN}
    secrets: inherit
\`\`\`

<details><summary>Notes</summary>

${leadingComment(source) || '_No notes._'}

</details>

### Inputs

${inputTable(call?.inputs, { withType: true })}${secretTable(call?.secrets)}
### Outputs

${outputTable(call?.outputs)}`;
  })
  .join('\n---\n\n');

emit(
  join(ROOT, 'docs', 'WORKFLOWS.md'),
  `# Reusable workflow reference

${GENERATED_NOTE}

Every workflow here is called with \`uses:\`, not copied. Pin to \`@${PIN}\` for the moving
major, or to an exact release for a frozen pipeline — see
[VERSIONING.md](VERSIONING.md).

Each one checks this repo out at \`job.workflow_sha\` so the composite actions it runs
always match the workflow version you pinned. You do not need to do anything for that to
work; it is explained in [CONSUMING.md](CONSUMING.md).

---

${workflowPages}
`,
);

// ── catalog tables in the root README ──────────────────────────────────────────────────

const readmePath = join(ROOT, 'README.md');
if (existsSync(readmePath)) {
  const readme = readFileSync(readmePath, 'utf8');

  const actionRows = actions
    .map(({ name, dir }) => {
      const doc = parse(readFileSync(join(dir, 'action.yml'), 'utf8'));
      return `| [\`${name}\`](actions/${name}/) | ${cell(doc.description)} |`;
    })
    .join('\n');

  const workflowRows = workflows
    .map(({ file, source, doc }) => {
      const slug = basename(file, '.yml');
      // A workflow has no top-level `description:`, so the summary comes from its header
      // comment — the first paragraph, unwrapped, cut at the first sentence. Splitting on
      // a colon would truncate "Python CI: lint, tests, coverage" to "Python CI".
      const paragraph = leadingComment(source).split(/\n\s*\n/)[0].replace(/\s*\n\s*/g, ' ').trim();
      const sentence = /^(.*?[.!?])(\s|$)/.exec(paragraph)?.[1] ?? paragraph;
      const summary =
        (sentence.length > 150 ? `${sentence.slice(0, 147).replace(/\s+\S*$/, '')}…` : sentence) || doc.name;
      return `| [\`${slug}\`](docs/WORKFLOWS.md#${slug}) | ${cell(summary)} |`;
    })
    .join('\n');

  const blocks = {
    actions: `| Action | What it does |\n|---|---|\n${actionRows}`,
    workflows: `| Workflow | What it does |\n|---|---|\n${workflowRows}`,
  };

  let next = readme;
  for (const [key, table] of Object.entries(blocks)) {
    const start = `<!-- AUTOGEN:${key} -->`;
    const end = `<!-- /AUTOGEN:${key} -->`;
    const pattern = new RegExp(`${start}[\\s\\S]*?${end}`);
    if (!pattern.test(next)) {
      console.warn(`⚠️  README.md has no ${start} … ${end} block; skipping the ${key} catalog.`);
      continue;
    }
    next = next.replace(pattern, `${start}\n${table}\n${end}`);
  }
  emit(readmePath, next);
}

// ── report ─────────────────────────────────────────────────────────────────────────────

if (CHECK) {
  if (drifted.length === 0) {
    console.log('✅ Generated docs are up to date.');
    process.exit(0);
  }
  console.error(`❌ ${drifted.length} generated file(s) are stale:\n`);
  for (const file of drifted) console.error(`  ${file}`);
  console.error('\nRun `make docs` and commit the result.');
  if (process.env.GITHUB_ACTIONS) {
    console.log(`::error title=Stale docs::Run 'make docs' and commit: ${drifted.join(', ')}`);
  }
  process.exit(1);
}

console.log(
  written.length === 0
    ? '✅ Docs already up to date.'
    : `✅ Wrote ${written.length} file(s):\n${written.map((f) => `  ${f}`).join('\n')}`,
);
